#!/usr/bin/env zsh

rm -rf $HOME/.local/share/TreeViewer/modules*

sudo mkdir -p /usr/local/bin/

sudo rm -f /usr/local/bin/TreeViewer /usr/local/bin/TreeViewerCommandLine

sudo ln -s /Applications/TreeViewer.app/Contents/MacOS/TreeViewer /Applications/TreeViewer.app/Contents/MacOS/TreeViewerCommandLine /usr/local/bin/
